In [3]:
from __future__ import print_function
import torch

In [4]:
x = torch.rand(3, 5)
print(x)


tensor([[0.9805, 0.7701, 0.0689, 0.7715, 0.0510],
        [0.4500, 0.5186, 0.6462, 0.7537, 0.0807],
        [0.8783, 0.4908, 0.0641, 0.7992, 0.1185]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7375,  0.3727,  0.5377],
        [-1.0006,  0.3649, -1.0035],
        [-1.2677,  1.2349,  1.1876],
        [-1.0895, -0.2490, -0.1340],
        [ 0.2240,  1.1063,  0.4883]])


In [8]:
print(x.size())


torch.Size([5, 3])


In [10]:
type(x.size())

torch.Size

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3394,  0.9521,  0.7148],
        [-0.7299,  1.1319, -0.0758],
        [-1.1259,  1.4259,  1.8836],
        [-0.1393,  0.3494, -0.0239],
        [ 0.9567,  1.4518,  1.2815]])


In [12]:
print(torch.add(x, y))

tensor([[-0.3394,  0.9521,  0.7148],
        [-0.7299,  1.1319, -0.0758],
        [-1.1259,  1.4259,  1.8836],
        [-0.1393,  0.3494, -0.0239],
        [ 0.9567,  1.4518,  1.2815]])


In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3394,  0.9521,  0.7148],
        [-0.7299,  1.1319, -0.0758],
        [-1.1259,  1.4259,  1.8836],
        [-0.1393,  0.3494, -0.0239],
        [ 0.9567,  1.4518,  1.2815]])


In [15]:
y.add(x)
print(y)

tensor([[0.3981, 0.5794, 0.1770],
        [0.2707, 0.7671, 0.9277],
        [0.1418, 0.1910, 0.6960],
        [0.9502, 0.5984, 0.1101],
        [0.7327, 0.3455, 0.7932]])


In [16]:
print(x[:, 1])

tensor([ 0.3727,  0.3649,  1.2349, -0.2490,  1.1063])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
print(x)
print(y)
print(z)

tensor([[ 0.4066,  0.6646,  0.5471, -0.6558],
        [ 0.2521,  1.1696,  1.3784,  1.1207],
        [ 0.0285,  0.2369, -1.8175, -0.4862],
        [ 0.3470,  0.4334, -0.1770, -0.7658]])
tensor([ 0.4066,  0.6646,  0.5471, -0.6558,  0.2521,  1.1696,  1.3784,  1.1207,
         0.0285,  0.2369, -1.8175, -0.4862,  0.3470,  0.4334, -0.1770, -0.7658])
tensor([[ 0.4066,  0.6646,  0.5471, -0.6558,  0.2521,  1.1696,  1.3784,  1.1207],
        [ 0.0285,  0.2369, -1.8175, -0.4862,  0.3470,  0.4334, -0.1770, -0.7658]])


In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1503])
0.1503196805715561


In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)

tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
print(x)

tensor([0.1503])


In [29]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!